const colors = {
  primary: "#0D9488",
  primaryLight: "#14B8A6",
  primaryDark: "#0F766E",
  secondary: "#5EEAD4",
  secondaryLight: "#99F6E4",
  secondaryDark: "#14B8A6",
  accent: "#FFE66D",
  accentDark: "#F5D442",
  background: "#F6FBF9",
  backgroundDark: "#102A29",
  surface: "#FFFFFF",
  surfaceDark: "#1E1E1E",
  text: "#183D3C",
  textLight: "#67817E",
  textDark: "#F0FFFD",
  textSecondaryDark: "#B5D1CC",
  border: "#DDEDE8",
  borderDark: "#274B47",
  success: "#00B894",
  warning: "#FDCB6E",
  error: "#E74C3C",
  calendar: {
    blue: "#74B9FF",
    green: "#55EFC4",
    purple: "#A29BFE",
    orange: "#FAB1A0",
    pink: "#FD79A8",
    yellow: "#FFEAA7",
  },
  memberColors: [
    "#FF6B6B",
    "#4ECDC4",
    "#74B9FF",
    "#A29BFE",
    "#FAB1A0",
    "#55EFC4",
  ],
};

export default {
  light: {
    text: colors.text,
    textSecondary: colors.textLight,
    background: colors.background,
    surface: colors.surface,
    tint: colors.primary,
    tabIconDefault: colors.textLight,
    tabIconSelected: colors.primary,
    border: colors.border,
    primary: colors.primary,
    primaryLight: colors.primaryLight,
    secondary: colors.secondary,
    accent: colors.accent,
    success: colors.success,
    warning: colors.warning,
    error: colors.error,
    calendar: colors.calendar,
    memberColors: colors.memberColors,
  },
  dark: {
    text: colors.textDark,
    textSecondary: colors.textSecondaryDark,
    background: colors.backgroundDark,
    surface: colors.surfaceDark,
    tint: colors.primaryLight,
    tabIconDefault: colors.textSecondaryDark,
    tabIconSelected: colors.primaryLight,
    border: colors.borderDark,
    primary: colors.primary,
    primaryLight: colors.primaryLight,
    secondary: colors.secondary,
    accent: colors.accent,
    success: colors.success,
    warning: colors.warning,
    error: colors.error,
    calendar: colors.calendar,
    memberColors: colors.memberColors,
  },
};
